# Generated by Django 4.2.25 on 2025-12-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechCategory',
            fields=[
                ('category_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='products/', verbose_name='Изображение')),
                ('tech_type', models.CharField(max_length=100, verbose_name='Тип устройства')),
                ('print_type', models.CharField(max_length=100, verbose_name='Тип печати')),
                ('print_technique', models.CharField(max_length=100, verbose_name='Технология печати')),
                ('placement', models.CharField(max_length=100, verbose_name='Размещение')),
                ('productivity', models.CharField(max_length=100, verbose_name='Кол-во страниц в месяц')),
                ('double_print', models.CharField(max_length=100, verbose_name='Автоматическая двусторонняя печать')),
                ('print_resolution', models.CharField(max_length=100, verbose_name='Макс. разрешение печати')),
                ('print_speed', models.CharField(max_length=100, verbose_name='Скорость печати')),
                ('warm_up_time', models.CharField(max_length=100, verbose_name='Время разогрева')),
                ('first_print_time', models.CharField(max_length=100, verbose_name='Время первого отпечатка')),
                ('scanner_type', models.CharField(max_length=100, verbose_name='Тип сканера/реверс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_items', to='app.techcategory', verbose_name='Категория')),
            ],
        ),
    ]
