# Generated by Django 4.2.25 on 2025-12-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='double_print',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автоматическая двусторонняя печать'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='first_print_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время первого отпечатка'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='placement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размещение'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='print_resolution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Макс. разрешение печати'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='print_speed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Скорость печати'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='print_technique',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Технология печати'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='print_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип печати'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='productivity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кол-во страниц в месяц'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='scanner_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип сканера/реверс'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='tech_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='warm_up_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время разогрева'),
        ),
    ]
