# Generated by Django 5.2.8 on 2026-01-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость (₽)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type_label', models.CharField(blank=True, max_length=255, verbose_name='Тип')),
                ('format_field', models.CharField(blank=True, max_length=100, verbose_name='Формат')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='Гарантия')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость (₽/мес)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type_label', models.CharField(blank=True, default='Подписка на услугу', max_length=255, verbose_name='Тип')),
                ('payment_period', models.CharField(blank=True, default='Ежемесячно', max_length=100, verbose_name='Период оплаты')),
                ('min_term', models.CharField(blank=True, max_length=100, verbose_name='Минимальный срок')),
                ('support', models.CharField(blank=True, max_length=255, verbose_name='Поддержка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Возможность товара',
                'verbose_name_plural': 'Возможности товара',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Возможность подписки',
                'verbose_name_plural': 'Возможности подписки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
