# Generated by Django 5.2.8

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_subscription_productfeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_log',
            name='phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^[\\d\\s\\+\\-\\(\\)]{10,25}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='audit_log',
            name='service',
            field=models.CharField(blank=True, max_length=255, verbose_name='Услуга'),
        ),
    ]
